PROBLEM 1

In [9]:
import numpy as np

In [10]:
x = np.random.random([5,5])

y = x.mean()
z = x.std()

norm = (x-y)/z
print(norm)

[[ 0.01577004  0.04131912 -0.60201631 -1.26258665  0.77612898]
 [ 1.38216273 -1.12644608 -0.33855934  0.0040262   1.10483695]
 [ 1.46353428  1.35168495 -1.95527829  0.55459374  0.05237159]
 [ 0.55954526 -0.98734067 -1.41591235  1.01839221 -0.2046042 ]
 [-0.88325296  0.90095542  1.22137269 -1.53219796 -0.13849936]]


PROBLEM 2

In [11]:
A = np.arange(1, 101).reshape(10, 10)**2

div_by_3 = A[A % 3 == 0]

print("Array of squares: \n", A)
print("\nElements divisible by 3: \n", div_by_3)
print("\nNumber of elements divisible by 3:", div_by_3.size)

Array of squares: 
 [[    1     4     9    16    25    36    49    64    81   100]
 [  121   144   169   196   225   256   289   324   361   400]
 [  441   484   529   576   625   676   729   784   841   900]
 [  961  1024  1089  1156  1225  1296  1369  1444  1521  1600]
 [ 1681  1764  1849  1936  2025  2116  2209  2304  2401  2500]
 [ 2601  2704  2809  2916  3025  3136  3249  3364  3481  3600]
 [ 3721  3844  3969  4096  4225  4356  4489  4624  4761  4900]
 [ 5041  5184  5329  5476  5625  5776  5929  6084  6241  6400]
 [ 6561  6724  6889  7056  7225  7396  7569  7744  7921  8100]
 [ 8281  8464  8649  8836  9025  9216  9409  9604  9801 10000]]

Elements divisible by 3: 
 [   9   36   81  144  225  324  441  576  729  900 1089 1296 1521 1764
 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056
 7569 8100 8649 9216 9801]

Number of elements divisible by 3: 33
